services:

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
    ports:
      - '5432:5432'